name: Image Combiner
version: "1.1.1"
slug: image_combiner
description: API service to combine up to 4 images with key-based retrieval and Redis caching
url: https://github.com/FernandoWahl/image-combiner-addon
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: services
boot: auto
init: false
ports:
  5000/tcp: 5000
ports_description:
  5000/tcp: Image Combiner API port
webui: http://[HOST]:[PORT:5000]
panel_icon: mdi:image-multiple
panel_title: Image Combiner
options:
  max_images: 4
  image_quality: 85
  cell_width: 400
  cell_height: 300
  timeout: 10
  redis_host: "localhost"
  redis_port: 6379
  redis_password: ""
  cache_ttl: 600
  enable_cache: true
  redis_required: true
schema:
  max_images: int(1,4)
  image_quality: int(50,100)
  cell_width: int(200,800)
  cell_height: int(200,600)
  timeout: int(5,30)
  redis_host: str
  redis_port: int(1,65535)
  redis_password: str?
  cache_ttl: int(60,3600)
  enable_cache: bool
  redis_required: bool
