name: Image Combiner
version: "1.0.0"
slug: image_combiner
description: API service to combine up to 4 images into a single composite image
url: https://github.com/FernandoWahl/image-combiner-addon
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: services
boot: auto
init: false
ports:
  5000/tcp: 5000
ports_description:
  5000/tcp: Image Combiner API port
webui: http://[HOST]:[PORT:5000]
panel_icon: mdi:image-multiple
panel_title: Image Combiner
options:
  max_images: 4
  image_quality: 85
  cell_width: 400
  cell_height: 300
  timeout: 10
schema:
  max_images: int(1,4)
  image_quality: int(50,100)
  cell_width: int(200,800)
  cell_height: int(200,600)
  timeout: int(5,30)
