build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-python:3.11-alpine3.18
  amd64: ghcr.io/home-assistant/amd64-base-python:3.11-alpine3.18
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Open Notebook"
  org.opencontainers.image.description: "An open source, privacy-focused alternative to Google's Notebook LM"
  org.opencontainers.image.source: "https://github.com/FernandoWahl/ha-addons"
  org.opencontainers.image.licenses: "MIT"
args:
  TEMPIO_VERSION: "2021.09.0"
