name: Open Notebook
version: "3.0.1"
slug: open_notebook
description: "Pure interface to original Open Notebook - PostgreSQL compatible"
url: https://github.com/FernandoWahl/ha-addons
arch:
  - aarch64
  - amd64
startup: services
boot: auto
init: false
ports:
  8501/tcp: 8501
  8000/tcp: 8000
ports_description:
  8501/tcp: Streamlit Web Interface
  8000/tcp: FastAPI Backend
webui: http://[HOST]:[PORT:8501]
panel_icon: mdi:notebook-outline
panel_title: Open Notebook
options:
  # Database Configuration
  database_type: "postgresql"
  postgres_host: ""
  postgres_port: 5432
  postgres_database: "open_notebook"
  postgres_user: ""
  postgres_password: ""
  
  # AI Model Configuration
  openai_api_key: ""
  anthropic_api_key: ""
  groq_api_key: ""
  google_api_key: ""
  mistral_api_key: ""
  deepseek_api_key: ""
  
  # Ollama Configuration
  ollama_base_url: ""
  
  # Application Settings
  debug: false
  log_level: "INFO"
  max_file_size: 50
  allowed_file_types: ["pdf", "txt", "md", "docx", "html"]
  
  # Security
  enable_auth: false
  auth_username: ""
  auth_password: ""

schema:
  # Database Configuration
  database_type: match(postgresql|sqlite)
  postgres_host: str?
  postgres_port: int(1,65535)?
  postgres_database: str?
  postgres_user: str?
  postgres_password: password?
  
  # AI Model Configuration
  openai_api_key: password?
  anthropic_api_key: password?
  groq_api_key: password?
  google_api_key: password?
  mistral_api_key: password?
  deepseek_api_key: password?
  ollama_base_url: str?
  
  # Application Settings
  debug: bool
  log_level: match(DEBUG|INFO|WARNING|ERROR)
  max_file_size: int(1,500)
  allowed_file_types: [str]
  enable_auth: bool
  auth_username: str?
  auth_password: password?

map:
  - share:rw
  - config:rw
  - media:rw
  - data:rw
