name: Open Notebook
version: "0.3.3"
slug: open_notebook
description: An open source, privacy-focused alternative to Google's Notebook LM
url: https://github.com/FernandoWahl/ha-addons
arch:
  - aarch64
  - amd64
startup: services
boot: auto
init: false
ports:
  8501/tcp: 8501
ports_description:
  8501/tcp: Streamlit Web Interface
webui: http://[HOST]:[PORT:8501]
panel_icon: mdi:notebook-outline
panel_title: Open Notebook
options:
  debug: false
schema:
  debug: bool
map:
  - share:rw
  - config:rw
