name: Open Notebook
version: "0.4.1"
slug: open_notebook
description: An open source, privacy-focused alternative to Google's Notebook LM for research and note-taking
url: https://github.com/FernandoWahl/ha-addons
arch:
  - aarch64
  - amd64
startup: services
boot: auto
init: false
ports:
  8501/tcp: 8501
  8000/tcp: 8000
ports_description:
  8501/tcp: Streamlit Web Interface
  8000/tcp: FastAPI Backend
webui: http://[HOST]:[PORT:8501]
panel_icon: mdi:notebook-outline
panel_title: Open Notebook
options:
  # Database Configuration
  database_url: "memory"
  database_user: "root"
  database_password: "root"
  
  # AI Model Configuration
  openai_api_key: ""
  anthropic_api_key: ""
  groq_api_key: ""
  google_api_key: ""
  mistral_api_key: ""
  deepseek_api_key: ""
  
  # Ollama Configuration
  ollama_base_url: ""
  
  # Application Settings
  debug: false
  log_level: "INFO"
  max_file_size: 50
  allowed_file_types: ["pdf", "txt", "md", "docx", "html"]
  
  # Security
  enable_auth: false
  auth_username: ""
  auth_password: ""

schema:
  database_url: str
  database_user: str
  database_password: str
  openai_api_key: str?
  anthropic_api_key: str?
  groq_api_key: str?
  google_api_key: str?
  mistral_api_key: str?
  deepseek_api_key: str?
  ollama_base_url: str?
  debug: bool
  log_level: match(DEBUG|INFO|WARNING|ERROR)
  max_file_size: int(1,500)
  allowed_file_types: [str]
  enable_auth: bool
  auth_username: str?
  auth_password: str?

map:
  - share:rw
  - config:rw
  - media:rw
